from enum import Enum

class InjectionExtractionState(Enum):
    IDLE = "IDLE"
    BROWSER_OPEN = "BROWSER_OPEN"
    PAGE_PREPARED = "PAGE_PREPARED"
    PROMPT_INJECTED = "PROMPT_INJECTED"
    IMAGES_GENERATED = "IMAGES_GENERATED"
    IMAGES_EXTRACTED = "IMAGES_EXTRACTED"
