from .browser_management import browser_management_router
from .image_generation import image_generation_router
from .prompt_injection import prompt_injection_router
from .image_extraction import image_extraction_router
from .routine import routine_router
